var App;

App = {};


/*
  Init
 */

App.init = function() {
  App.canvas = document.createElement('canvas');
  App.canvas.height = 400;
  App.canvas.width = 800;
  document.getElementsByTagName('article')[0].appendChild(App.canvas);
  App.ctx = App.canvas.getContext("2d");
  App.ctx.fillStyle = "solid";
  array = ["#000","#FF0000", "#336600", "#0000CC", "#FF3399", "#FFFF66", "#FF33FF", "#660033"]
  App.strokeColor = array[Math.floor(Math.random() * array.length)];
  App.ctx.lineWidth = 5;
  App.ctx.lineCap = "round";
  App.socket = io.connect('http://localhost:4000');
  App.socket.on('draw', function(data) {
    return App.draw(data.x, data.y, data.type, data.color);
  });

  App.socket.on('context', function(data) {
    console.log("context received: " + data.ctx);
    if (data.ctx){
        var img = new Image();
        img.src = data.ctx;
        return App.ctx.drawImage(img, 0, 0);
      }
  });
  App.draw = function(x, y, type, color) {
    App.ctx.strokeStyle = color;
    if (type === "dragstart") {
      App.ctx.beginPath();
      return App.ctx.moveTo(x, y);
    } else if (type === "drag") {
      App.ctx.lineTo(x, y);
      return App.ctx.stroke();
    } else {
      return App.ctx.closePath();
    }
  };
};


/*
  Draw Events
 */

$('canvas').live('drag dragstart dragend', function(e) {
  var color, offset, type, x, y;
  type = e.handleObj.type;
  offset = 0;$(this).offset();
  color = App.strokeColor;
  e.offsetX = e.pageX - this.offsetLeft;
  e.offsetY = e.pageY - this.offsetTop;
  x = e.offsetX;
  y = e.offsetY;
  App.draw(x, y, type, color);
  App.socket.emit('drawClick', {
    x: x,
    y: y,
    type: type,
    color: color,
    ctx: App.canvas.toDataURL("image/png")
  });
});

$(function() {
  return App.init();
});

// ---
// generated by coffee-script 1.9.2